export const queryKeys = {
  ACADEMY_LIST: 'academyList',
  CHALLENGE_LIST: 'challengeList',
  ATTENDEE_LIST: 'AttendeeList',
  ACADEMY_STUDENT_DETAIL_LIST: 'academyStudentDetailList',
  ACADEMY_STUDENT_LIST: 'academyStudentList',
  ACADEMY_INSTRUCTOR_LIST: 'academyInstructorList',
  CHALLENGE_STUDENT_PROGRESS_LIST: 'challengeStudentProgressList',
  CHALLENGE_STUDENT_CONTENTS: 'challengeStudentContents',
  PUBLIC_CHALLENGE_LIST: 'publicChallengeList',
  INVITATION_CODE: 'invitationCode',
  CHALLENGE_FEED_LIST: 'feedChallengeList',
  PROFILE: 'profile',
  STUDENT_CHALLENGE_LIST: 'studentChallengeList',
  CHALLENGE_MARKET: 'challengeMarket',
  MY_CHALLENGE_CONTENTS: 'myChallengeContents',
} as const;
