enum ACADEMY_ROLE {
  INSTRUCTOR = 'INSTRUCTOR',
  PRINCIPAL = 'PRINCIPAL',
  STUDENT = 'STUDENT',
}

enum FREEMIUM_TIRE {
  BASIC = 'BASIC',
  ENTERPRISE = 'ENTERPRISE',
  PREMIUM = 'PREMIUM',
  STANDARD = 'STANDARD',
  STARTER = 'STARTER',
}

export { ACADEMY_ROLE, FREEMIUM_TIRE };
