enum SOCIAL_TYPE {
  APPLE = 'APPLE',
  GOOGLE = 'GOOGLE',
  KAKAO = 'KAKAO',
  LOCAL = 'LOCAL',
  NAVER = 'NAVER',
}

enum GLOBAL_ROLE {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_USER = 'ROLE_USER',
}

export { GLOBAL_ROLE, SOCIAL_TYPE };
