enum CHALLENGE_LOG_APPROVAL_STATUS {
  APPROVED = 'APPROVED',
  INCOMPLETE_CHALLENGE = 'INCOMPLETE_CHALLENGE',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}

enum CHALLENGE_LOG_SUBMISSION_STATUS {
  ALL_LOGS_SUBMITTED = 'ALL_LOGS_SUBMITTED',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_STARTED = 'NOT_STARTED',
  SUBMISSION_FAILED = 'SUBMISSION_FAILED',
}

export { CHALLENGE_LOG_APPROVAL_STATUS, CHALLENGE_LOG_SUBMISSION_STATUS };
