enum EMAIL_VERIFIED_TYPE {
  ACADEMY_REGISTRATION_VERIFIED = 'ACADEMY_REGISTRATION_VERIFIED',
  JOIN_VERIFIED = 'JOIN_VERIFIED',
  UPDATE_PASSWORD_VERIFIED = 'UPDATE_PASSWORD_VERIFIED',
}

export { EMAIL_VERIFIED_TYPE };
